<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <AssemblyName>ChatBound</AssemblyName>
    <RootNamespace>ChatBound</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="ChatBound.Server\**" />
    <None Remove="ChatBound.Server\**" />
    <Content Remove="ChatBound.Server\**" />
    <None Include="Dictionaries\**\*" CopyToOutputDirectory="PreserveNewest" />
    <None Include="ChatBound.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
